#!/usr/bin/env bash
# AI-Relay-Service node base image entrypoint (T-119).
#
# Translates environment variables into the files the node stack reads from
# ~/.relay (relay_config.json, node.yaml, ai-relay-agent.json, token) and
# then execs the node-daemon (SSE, event-driven).
#
# Environment variables (all optional unless noted):
#   RELAY_URL          — relay base URL, e.g. https://relay.example.com (REQUIRED)
#   NODE_NAME          — human-friendly node name (default: container hostname)
#   NODE_PROFILE       — profile name to publish from profiles.d (optional)
#   NODE_ROLE          — node role passed to the register call: "worker" (default)
#                       or "service". Storage/SSN use "service".
#   NODE_ENDPOINT      — upstream endpoint the relay can reach this node on
#                       (optional; needed for bridge-route upstream URLs).
#   NODE_REGISTRATION_SECRET — pre-created registration secret (rs_...) the
#                       node uses to authenticate the register call. Optional;
#                       when unset the node registers without one (the relay
#                       may require approval afterwards).
#   RELAY_HEARTBEAT_INTERVAL — overrides heartbeat_interval (seconds)
#   RELAY_CLAIM_INTERVAL     — overrides claim_interval (seconds)
#   RELAY_REQUEST_TIMEOUT    — overrides request_timeout (seconds)
#   RELAY_LOG_LEVEL          — log level (DEBUG/INFO/WARNING/ERROR)
#
# The entrypoint is idempotent: on subsequent starts it reuses the existing
# meta + token files and only refreshes relay_config.json + node.yaml from
# the current env. The daemon is exec'd as PID 1 (via tini) so signals reach
# it directly.

set -euo pipefail

RELAY_DIR="${HOME}/.relay"
CONFIG_JSON="${RELAY_DIR}/relay_config.json"
META_JSON="${RELAY_DIR}/ai-relay-agent.json"
TOKEN_FILE="${RELAY_DIR}/ai-relay-agent.token"
NODE_YAML="${RELAY_DIR}/node.yaml"
PROFILES_DIR="${RELAY_DIR}/profiles.d"

mkdir -p "${RELAY_DIR}" "${PROFILES_DIR}"

# --- RELAY_URL: explicit env, else mDNS discovery (T-152) ----------------
# RELAY_URL is preferred. When unset, try to discover the relay on the
# local network via mDNS (the relay advertises `AI Relay Service._http._tcp.local.`).
# If neither yields a URL, fail fast.
if [ -z "${RELAY_URL:-}" ]; then
    echo "[entrypoint] RELAY_URL not set — attempting mDNS discovery..."
    DISCOVERED=$(python3 - <<'PY'
import sys
try:
    from nodes.common.relay_client import _discover_relay_mdns
    url = _discover_relay_mdns(timeout=3.0)
    if url:
        print(url)
except Exception as exc:
    print(f"mDNS discovery failed: {exc}", file=sys.stderr)
PY
    )
    if [ -n "${DISCOVERED}" ]; then
        RELAY_URL="${DISCOVERED}"
        # Export so the register script (which reads os.environ["RELAY_URL"])
        # sees it even though the operator did not set it.
        export RELAY_URL
        echo "[entrypoint] mDNS discovered relay at ${RELAY_URL}"
    else
        echo "[entrypoint] ERROR: RELAY_URL is required and mDNS discovery found no relay." >&2
        echo "[entrypoint]        Set RELAY_URL (e.g. https://relay.example.com) or ensure" >&2
        echo "[entrypoint]        the relay advertises itself via mDNS on this network." >&2
        exit 1
    fi
fi

# Strip a trailing slash so base_url is consistent with the node client.
BASE_URL="${RELAY_URL%/}"

# Node name: explicit env, else container hostname, else fallback.
NODE_NAME="${NODE_NAME:-$(hostname 2>/dev/null || echo node)}"
NODE_ROLE="${NODE_ROLE:-worker}"

# --- relay_config.json ----------------------------------------------------
# Written on every start so an operator can change RELAY_URL by restarting.
cat > "${CONFIG_JSON}" <<EOF
{
  "base_url": "${BASE_URL}",
  "heartbeat_interval": ${RELAY_HEARTBEAT_INTERVAL:-8},
  "claim_interval": ${RELAY_CLAIM_INTERVAL:-5},
  "status_interval": 7200,
  "rt_refresh_before_seconds": 86400,
  "rs_refresh_before_seconds": 3600,
  "request_timeout": ${RELAY_REQUEST_TIMEOUT:-10},
  "task_timeout": 600,
  "log_level": "${RELAY_LOG_LEVEL:-INFO}"
}
EOF
echo "[entrypoint] relay_config.json written (base_url=${BASE_URL})"

# --- node.yaml -------------------------------------------------------------
# Only (re)write node.yaml when no profile was published yet OR when the
# NODE_PROFILE env is set (explicit override). A service image that ships
# its own node.yaml via COPY wins — we only seed an empty one here.
if [ ! -f "${NODE_YAML}" ]; then
    cat > "${NODE_YAML}" <<EOF
# Auto-generated by docker/nodes/base entrypoint. Edit or replace with a service
# profile (see docker/<service>/node.yaml). Capabilities are optional — a
# node can register without any and add them later at runtime.
node_name: ${NODE_NAME}
EOF
    echo "[entrypoint] node.yaml seeded (node_name=${NODE_NAME})"
fi

# Publish a profile from profiles.d when NODE_PROFILE is set. This copies
# the named profile to node.yaml so the daemon picks up its capabilities.
# The copy happens on EVERY start (not just first) so an image update that
# ships a newer profile actually reaches the persistent node.yaml — the
# persistent volume would otherwise keep a stale capability set forever
# (T-163: long_run flag was missing on the QNAP node).
if [ -n "${NODE_PROFILE:-}" ]; then
    PROFILE_FILE="${PROFILES_DIR}/${NODE_PROFILE}"
    if [ ! -f "${PROFILE_FILE}" ]; then
        # Try with a .yaml/.yml extension if the bare name did not resolve.
        if [ -f "${PROFILE_FILE}.yaml" ]; then
            PROFILE_FILE="${PROFILE_FILE}.yaml"
        elif [ -f "${PROFILE_FILE}.yml" ]; then
            PROFILE_FILE="${PROFILE_FILE}.yml"
        else
            echo "[entrypoint] ERROR: NODE_PROFILE='${NODE_PROFILE}' not found" >&2
            echo "[entrypoint]        in ${PROFILES_DIR}" >&2
            exit 1
        fi
    fi
    cp "${PROFILE_FILE}" "${NODE_YAML}"
    echo "[entrypoint] node.yaml published from profile '${NODE_PROFILE}'"
fi

# --- first-start registration ---------------------------------------------
# When no meta file exists yet the node has never registered. We register
# it now via the relay's /relay/v2/auth/register endpoint and persist the
# returned node_id + token so the daemon can pick them up. On subsequent
# starts the existing meta + token are reused.
if [ ! -f "${META_JSON}" ]; then
    echo "[entrypoint] no metadata found — registering node '${NODE_NAME}' with relay"

    # Build the register payload. The capabilities list comes from the
    # published node.yaml if present; otherwise we register an empty list
    # and let the daemon publish capabilities via heartbeat.
    REGISTER_PAYLOAD=$(python3 - <<'PY'
import json, os, yaml
caps = []
node_yaml = os.path.expanduser("~/.relay/node.yaml")
try:
    with open(node_yaml) as f:
        prof = yaml.safe_load(f) or {}
    caps = prof.get("capabilities", []) or []
except Exception:
    pass
# Strip handler/claimable/timeout fields the register endpoint does not
# understand — the register endpoint only persists name+version.
clean = []
for c in caps:
    if isinstance(c, dict) and "name" in c:
        clean.append({"name": c["name"], "version": str(c.get("version", "1.0.0"))})
print(json.dumps({
    "node_name": os.environ.get("NODE_NAME", "node"),
    "endpoint": os.environ.get("NODE_ENDPOINT") or None,
    "capabilities": clean,
    "role": os.environ.get("NODE_ROLE", "worker"),
}))
PY
    )
    # Register. We use python+httpx (installed in the base image) rather
    # than curl so we don't add a system dependency. The payload is passed
    # as a JSON file (not string-interpolated) so `null`/`true`/`false`
    # values survive — interpolating JSON into Python source breaks on
    # `null` (NameError: name 'null' is not defined).
    REGISTER_PAYLOAD_FILE="${RELAY_DIR}/register-payload.json"
    printf '%s' "${REGISTER_PAYLOAD}" > "${REGISTER_PAYLOAD_FILE}"
    python3 - <<PY
import json, os, sys
import httpx
base_url = os.environ["RELAY_URL"].rstrip("/")
with open(os.path.expanduser("~/.relay/register-payload.json")) as f:
    payload = json.load(f)
headers = {}
secret = os.environ.get("NODE_REGISTRATION_SECRET")
if secret:
    headers["X-Registration-Secret"] = secret
try:
    r = httpx.post(f"{base_url}/relay/v2/auth/register", json=payload, headers=headers, timeout=30)
    r.raise_for_status()
except httpx.HTTPError as exc:
    print(f"[entrypoint] ERROR: registration failed: {exc}", file=sys.stderr)
    sys.exit(1)
data = r.json()
meta = {
    "base_url": base_url,
    "node_id": data["node_id"],
    "node_name": data.get("node_name", payload["node_name"]),
    "registration_secret": data.get("registration_secret"),
    "capabilities": payload["capabilities"],
}
rel = os.path.expanduser("~/.relay")
import pathlib
pathlib.Path(rel).mkdir(parents=True, exist_ok=True)
pathlib.Path(rel, "ai-relay-agent.json").write_text(json.dumps(meta, indent=2))
token = data.get("token")
if token:
    pathlib.Path(rel, "ai-relay-agent.token").write_text(json.dumps({"token": token, "expires_at": None}) + "\n")
status = data.get("status", "pending")
print(f"[entrypoint] registered node_id={data['node_id']} status={status}")
if status == "pending":
    print("[entrypoint] node is pending approval — approve it via dashboard or admin API")
PY
    rm -f "${REGISTER_PAYLOAD_FILE}"
else
    echo "[entrypoint] reusing existing metadata (${META_JSON})"
fi

# exec so node-daemon becomes a direct child and receives SIGTERM/SIGINT.
exec "$@"